include: package:lint/analysis_options.yaml

analyzer:
  exclude: [
      lib/**.g.dart,
      lib/generated/**,
      lib/generated_plugin_registrant.dart,
      lib/styles/app_icons.dart,
  ]

linter:
  rules:
    avoid_bool_literals_in_conditional_expressions: false
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    prefer_single_quotes: true