name: hello_earth
description: Application to help teens with asperger.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  freezed: ^2.1.0+1
  flutter_bloc: ^8.1.1
  firebase_database: ^9.1.4
  flutter_secure_storage: ^6.0.0
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  equatable: ^2.0.5
  qr_flutter: ^4.0.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter

  json_serializable: ^6.3.2
  lint: ^1.10.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true