name: hello_earth
description: Application to help teens with asperger.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  freezed: ^2.1.0+1
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.1.0
  firebase_core: ^1.20.0
  firebase_auth: 3.6.2
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  equatable: ^2.0.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

  json_serializable: ^6.3.1
  lint: ^1.10.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true