name: hello_earth
description: Application to help teens with asperger.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_database: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.6
  freezed: ^2.2.1
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  mockito: ^5.3.2
  percent_indicator: ^4.0.1
  youtube_player_flutter: ^8.1.1
  visibility_detector: ^0.3.3
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter

  json_serializable: ^6.5.4
  lint: ^1.10.0

flutter:
  assets:
    - assets/svg_icons/
    - assets/png_icons/
  uses-material-design: true

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
