// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFxDdJVgKqRPhE6aqrN_krQ2-TcH-7uBw',
    appId: '1:983481189837:android:7cd1c320d0146fb45cb084',
    messagingSenderId: '983481189837',
    projectId: 'helloearth-7e025',
    databaseURL: 'https://helloearth-7e025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'helloearth-7e025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYip5RP-SERJYK7q-LaJrQdCfW7WzPcfw',
    appId: '1:983481189837:ios:2492565ca412e2555cb084',
    messagingSenderId: '983481189837',
    projectId: 'helloearth-7e025',
    databaseURL: 'https://helloearth-7e025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'helloearth-7e025.appspot.com',
    iosClientId: '983481189837-b4iprhk2ao3a41dkelieha6q696st1u4.apps.googleusercontent.com',
    iosBundleId: 'pl.umk.helloEarth',
  );
}
