// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSoIFQ2ivwQ6jTocjHSMPTZ8FeAid6jhs',
    appId: '1:327438767017:android:9a6fd4e27e5c7cc239aab8',
    messagingSenderId: '327438767017',
    projectId: 'helloearth-dev-cc175',
    databaseURL: 'https://helloearth-dev-cc175-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'helloearth-dev-cc175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCASsV20LRITzyd358Ui4c_a3ka_eb-gDA',
    appId: '1:327438767017:ios:7a42599dfdb19e8c39aab8',
    messagingSenderId: '327438767017',
    projectId: 'helloearth-dev-cc175',
    databaseURL: 'https://helloearth-dev-cc175-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'helloearth-dev-cc175.appspot.com',
    iosClientId: '327438767017-fuk63m8i7prqer79klo50o58hm7h78h6.apps.googleusercontent.com',
    iosBundleId: 'pl.umk.helloEarth.dev',
  );
}
